apiVersion: v2
description: JupyterHub itself
name: hub
version: "0.0.0"
kubeVersion: ">= 1.32.0-0"
dependencies:
  - name: jupyterhub
    version: "4.3.1"
    repository: "https://jupyterhub.github.io/helm-chart"
  - name: jupyterhub-home-nfs
    version: "1.2.0"
    repository: oci://ghcr.io/2i2c-org/jupyterhub-home-nfs
