apiVersion: v2
description: Support chart for jupyterhub clusters
name: support
version: "0.0.0"
kubeVersion: ">= 1.32.0-0"
dependencies:
  - name: traefik
    version: "37.3.0"
    repository: oci://ghcr.io/traefik/helm
  - name: prometheus
    version: "27.36.0"
    repository: https://prometheus-community.github.io/helm-charts
  - name: grafana
    version: "9.4.4"
    repository: https://grafana.github.io/helm-charts
